### ISSUE TITLE
How do I configure ansible-fail2ban to use the root user?

### ISSUE THREAD

**Issue by vraravam** [Oefenweb/ansible-fail2ban#44]
As per the docs,  I have put the following in the group_vars yml file:
```yaml
  fail2ban_bantime: 3600
  fail2ban_filterd_path: ../../../files/fail2ban/etc/fail2ban/filter.d/
  fail2ban_services:
    - name: nginx-bots
      port: http,https
      filter: nginx-bots
      logpath: /var/log/nginx/access.log*
      maxretry: 1
      bantime: 172800
      findtime: 86400
```
But, I keep getting the following error:
```bash
(item=[u'fail2ban']) => {"failed": true, "item": ["fail2ban"], "msg": "Failed to lock apt for exclusive operation"}
```
I thought that it might be related to some kind of apt process locking the db, but even after a reboot of the VM, I keep getting the same error. When I ssh into the box, I can do `apt-update` without any problems.
