### ISSUE TITLE
Idempotency issue with jail.local

### ISSUE THREAD

**Issue by maxlareo** [Oefenweb/ansible-fail2ban#48]
Hi there,

Each time I run my playbooks, I always get a changed with the [update configuration file - /etc/fail2ban/jail.local](https://github.com/Oefenweb/ansible-fail2ban/blob/master/tasks/main.yml#L28) task.

In the template [jail.local.j2](https://github.com/Oefenweb/ansible-fail2ban/blob/master/templates/etc/fail2ban/jail.local.j2#L108), the service.items() are not sorted and are in a different order at each run.

I use this kind of settings : 

```yaml
fail2ban_services:
    - name: ssh
      port: 2345
      filter: sshd
      logpath: /var/log/auth.log
      maxretry: 6
    - name: postfix
      port: smtp,ssmtp,submission
      filter: postfix
      logpath: /var/log/mail.log
```

I will make a pull request to propose a solution as soon as this issue get a number
