### ISSUE TITLE
Add support for dbpurgeage (required for recidive)

### ISSUE THREAD

**Issue by john-999** [Oefenweb/ansible-fail2ban#51]
The Role should ideally accept the below configuration's last line (but it does not set the value):
```
- name: "Install : fail2ban."
  include_role:
    name: oefenweb.fail2ban
  vars:
    fail2ban_dbpurgeage: 648000 # For use of the jail "[recidive]": Increase this value to e.g. 648000 (7.5 days)
```
Extract from the fail2ban docs (https://wiki.meurisse.org/wiki/Fail2Ban#Recidive) regarding the ```[recidive]``` jail:
```
# 2. If you increase bantime, you must increase value of dbpurgeage
#    to maintain entries for failed logins for sufficient amount of time.
#    The default is defined in fail2ban.conf and you can override it in fail2ban.local
```
