### ISSUE TITLE
Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?

### ISSUE THREAD

**Issue by chriswayg** [Oefenweb/ansible-fail2ban#58]
Previously ansible-fail2ban always worked for me on Debian. But now when using your unmodified role  (even with just the default sshd jail) I always get: 

> "Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?"

But when I install manually with the same configurations it works.  Tried multiple times with various settings, but can't figure out why it is not working:

```
root@proxmox:~# systemctl restart fail2ban; systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-08-13 16:28:50 PST; 8ms ago
     Docs: man:fail2ban(1)
  Process: 1190 ExecStartPre=/bin/mkdir -p /var/run/fail2ban (code=exited, status=0/SUCCESS)
 Main PID: 1197 (fail2ban-server)
    Tasks: 1 (limit: 4915)
   Memory: 1.7M
   CGroup: /system.slice/fail2ban.service
           └─1197 /usr/bin/python3 /usr/bin/fail2ban-server -xf start

Aug 13 16:28:50 proxmox systemd[1]: Starting Fail2Ban Service...
Aug 13 16:28:50 proxmox systemd[1]: Started Fail2Ban Service.

root@proxmox:~# fail2ban-client -v status 
 Loading configs for fail2ban under /etc/fail2ban 
   Loading files: ['/etc/fail2ban/fail2ban.conf']
   Loading files: ['/etc/fail2ban/fail2ban.local']
   Loading files: ['/etc/fail2ban/fail2ban.conf', '/etc/fail2ban/fail2ban.local']
 Using socket file /var/run/fail2ban/fail2ban.sock
 Using pid file /var/run/fail2ban/fail2ban.pid, [INFO] logging to /var/log/fail2ban.log
 Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?
```
_Tested on Debian 10 buster_

**When cutting the fail2ban role to its bare essentials it works again:**
```
root@proxmox:~# fail2ban-client -v status 
 Loading configs for fail2ban under /etc/fail2ban 
   Loading files: ['/etc/fail2ban/fail2ban.conf']
   Loading files: ['/etc/fail2ban/fail2ban.conf']
 Using socket file /var/run/fail2ban/fail2ban.sock
 Using pid file /var/run/fail2ban/fail2ban.pid, [INFO] logging to /var/log/fail2ban.log
Status
|- Number of jail:	2
`- Jail list:	proxmox, sshd
```

==== minimal fail2ban role ====
```
# tasks file for fail2ban
---
- name: Ensure, that fail2ban is installed on Debian.
  apt:
    name: fail2ban
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: update configuration file - /etc/fail2ban/jail.local
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: copy filter
  copy:
    src: proxmox.conf
    dest: /etc/fail2ban/filter.d/
  notify: restart fail2ban
```

```
# jail.local
[sshd]
enabled = true
port = 22,722
maxretry = 3

[proxmox]
enabled = true
port = https,http,8006
filter = proxmox
logpath = /var/log/daemon.log
maxretry = 3
```

```
# proxmox.conf filter
[Definition]
failregex = pvedaemon\[.*authentication failure; rhost=<HOST> user=.* msg=.*
ignoreregex =
```

```
# handlers file for fail2ban
---
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
```
