### ISSUE TITLE
Role cannot be run in check mode

### ISSUE THREAD

**Issue by prouveyrol** [Oefenweb/ansible-fail2ban#74]
When running a playbook using this role with the "-C" option, it will skip the following task
```
- name: get fail2ban version
  ansible.builtin.command: >
    fail2ban-server -V
  changed_when: false
  register: _fail2ban_version_raw
  tags:
    - configuration
    - fail2ban
    - fail2ban-install
 ```
 Resulting in the next task getting an error.
 I was going to make a PR, but actually, it already exists : https://github.com/Oefenweb/ansible-fail2ban/pull/73
