### ISSUE TITLE
Installed role / Role not found

### ISSUE THREAD

**Issue by MalteKiefer** [Oefenweb/ansible-fail2ban#78]
I have installed the role with this command:

`ansible-galaxy install oefenweb.fail2ban`

I try to build a playbook like this:

```yaml
---
- hosts: all
  roles:
    - fail2ban
  vars:
    fail2ban_banaction: 'ufw'
    fail2ban_services:
      - name: sshd
        maxretry: 5
        bantime: -1
```

This is my error that I get:

```bash
 ~/E/ansible  ansible-playbook -i inventory/host.yml playbooks/deploy_fail2ban.yml                                                                                                                                                                    2119ms  Do  4 Mai 11:24:37 2023
ERROR! the role 'fail2ban' was not found in /Users/xxx/Entwicklung/ansible/playbooks/roles:/Users/xxx/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/xxx/Entwicklung/ansible/playbooks

The error appears to be in '/Users/xxx/Entwicklung/ansible/playbooks/deploy_fail2ban.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - fail2ban
      ^ here
```
